### ISSUE TITLE
introduce a Boolean "sync" property in tournament collection

### ISSUE THREAD

**Issue by cschaffner** [regenworm/ScoreApp#5]
From the admin interface, one can choose whether a tournament should be "synced" with leaguevine or not.

**Comment by maxcww** [comment]
As in the sync each 10 minutes or with the sync when one updates a score.

Date: Sat, 16 Jan 2016 11:18:04 -0800

**Comment by cschaffner** [comment]
in the sync each 10 minutes. The update-score sync should be done in any case.
